"use client";

import { useEffect, useState, use } from "react";
import { Download } from "lucide-react";

export default function RekamMedisPublicPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const resolvedParams = use(params);
  const id = resolvedParams.id;

  const [data, setData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        // Nembak API tanpa token biar bisa diakses lewat scan QR
        const res = await fetch(
          `https://sadulur-api.vercel.app/api/admin/rm14?patientId=${id}`,
        );
        if (res.ok) {
          setData(await res.json());
        }
      } catch (error) {
        console.error("Gagal menarik data", error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchData();
  }, [id]);

  // 🚀 FUNGSI SAKTI BARU: Ganti ke Native Print (Anti Error lab color & Hasil Lebih Tajam)
  const handleDownloadPDF = () => {
    window.print(); // Nanti di HP/PC otomatis buka menu Print -> tinggal "Simpan sebagai PDF"
  };

  if (isLoading)
    return (
      <div className="p-10 text-center font-bold text-teal-600 animate-pulse">
        Membuka Dokumen Medis...
      </div>
    );

  if (!data)
    return (
      <div className="p-10 text-center font-bold text-red-500">
        Dokumen tidak ditemukan! (Atau API Backend mengunci akses publik).
      </div>
    );

  const ds = data.dischargeSummary || data || {};
  const meds = ds.medications || [];
  const userEmail = data.user?.email || "";
  const isAutoGenerated =
    userEmail.startsWith("pasien_") && userEmail.endsWith("@sadulur.com");
  const displayPass = "Sadulur123!";

  return (
    <div className="bg-gray-100 min-h-screen py-6 font-sans">
      {/* TOMBOL DOWNLOAD KHUSUS PASIEN / DOKTER (Sembunyi pas diprint) */}
      <div className="max-w-4xl mx-auto flex justify-center md:justify-end px-4 mb-6 print:hidden">
        <button
          onClick={handleDownloadPDF}
          className="bg-teal-600 text-white px-6 py-3 rounded-xl flex items-center gap-2 font-black shadow-xl hover:bg-teal-700 active:scale-95 transition-all w-full md:w-auto justify-center"
        >
          <Download size={22} /> UNDUH / CETAK PDF RESMI
        </button>
      </div>

      {/* ==============================================
          KONTEN PDF SINKRON 100% SAMA ADMIN
          ============================================== */}
      <div
        id="pdf-content"
        className="bg-white text-black max-w-4xl mx-auto font-serif text-sm leading-relaxed p-8 shadow-2xl print:shadow-none print:p-0 print:m-0"
      >
        <div className="print:break-after-page mb-10 print:mb-0">
          <div className="text-center border-b-[3px] border-black pb-4 mb-6">
            <h1 className="text-2xl font-black uppercase tracking-wide">
              RESUME MEDIS KEPULANGAN (RM 14)
            </h1>
            <p className="text-sm font-bold">
              SADULUR CARE INTERVENTION SYSTEM
            </p>
          </div>

          <table className="w-full mb-6">
            <tbody>
              <tr>
                <td className="w-48 font-bold align-top">No. Rekam Medis</td>
                <td className="w-4 align-top">:</td>
                <td className="align-top font-bold text-lg">{id}</td>
              </tr>
              <tr>
                <td className="font-bold align-top">Nama</td>
                <td className="align-top">:</td>
                <td className="align-top capitalize">
                  {data.user?.name || "-"}
                </td>
              </tr>
              <tr>
                <td className="font-bold align-top">Tgl Lahir</td>
                <td className="align-top">:</td>
                <td className="align-top">-</td>
              </tr>
              <tr>
                <td className="font-bold align-top">Ruangan</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.ruangan || "-"}</td>
              </tr>
              <tr>
                <td className="font-bold align-top">Tanggal Diisi</td>
                <td className="align-top">:</td>
                <td className="align-top">
                  {ds.createdAt
                    ? new Date(ds.createdAt).toLocaleDateString("id-ID", {
                        day: "numeric",
                        month: "long",
                        year: "numeric",
                      })
                    : "-"}
                </td>
              </tr>
              <tr>
                <td className="font-bold align-top pt-2">Diagnosa medis</td>
                <td className="align-top pt-2">:</td>
                <td className="align-top pt-2">{ds.diagnosaMedis || "-"}</td>
              </tr>
              <tr>
                <td className="font-bold align-top">Tindakan yang diberikan</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.tindakanDiberikan || "-"}</td>
              </tr>
              <tr>
                <td className="font-bold align-top">Nama Dokter</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.namaDokter || "-"}</td>
              </tr>
              <tr>
                <td className="font-bold align-top">Nama Perawat</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.namaPerawat || "-"}</td>
              </tr>
              <tr>
                <td className="font-bold align-top">Alamat Pasien</td>
                <td className="align-top">:</td>
                <td className="align-top border-b border-black w-full inline-block mt-4"></td>
              </tr>
            </tbody>
          </table>

          <h3 className="font-black bg-gray-200 px-2 py-1 mb-2 border border-black uppercase">
            Aktifitas
          </h3>
          <table className="w-full mb-6">
            <tbody>
              <tr>
                <td className="w-[45%] align-top">
                  Jenis aktifitas yang boleh di lakukan
                </td>
                <td className="w-4 align-top">:</td>
                <td className="align-top">
                  {ds.jenisAktifitas || ds.instruksiAktivitas || "-"}
                </td>
              </tr>
              <tr>
                <td className="align-top">Perubahan Posisi (ROM)</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.perubahanPosisi || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Eliminasi (Toilet Training)</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.eliminasi || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Alat bantu yang dapat digunakan</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.alatBantu || "-"}</td>
              </tr>
            </tbody>
          </table>

          <h3 className="font-black bg-gray-200 px-2 py-1 mb-2 border border-black uppercase">
            Perawatan Di rumah
          </h3>
          <table className="w-full mb-6">
            <tbody>
              <tr>
                <td className="w-[45%] align-top">
                  Tanda dan gejala yang perlu dilaporkan
                </td>
                <td className="w-4 align-top">:</td>
                <td className="align-top">{ds.tandaGejala || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Pengobatan yang dapat dilakukan</td>
                <td className="align-top">:</td>
                <td className="align-top">
                  {ds.pengobatanDiRumah || ds.perawatanRumah || "-"}
                </td>
              </tr>
            </tbody>
          </table>

          <h3 className="font-black bg-gray-200 px-2 py-1 mb-2 border border-black uppercase">
            Edukasi Kesehatan
          </h3>
          <table className="w-full">
            <tbody>
              <tr>
                <td className="w-[45%] align-top">Jadwal Kontrol</td>
                <td className="w-4 align-top">:</td>
                <td className="align-top">{ds.jadwalKontrolEdukasi || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Pemeriksaan Laboratorium Lanjutan</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.labLanjutan || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">
                  Pengertian & pemahaman efek samping obat
                </td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.pemahamanObat || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Obat-obat alternatif</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.obatAlternatif || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Pencegahan terhadap kekambuhan</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.pencegahanKekambuhan || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Edukasi lainnya</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.edukasiLainnya || "-"}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="print:pt-10 mt-10">
          <h3 className="font-black bg-gray-200 px-2 py-1 mb-2 border border-black uppercase">
            Diet
          </h3>
          <table className="w-full mb-6">
            <tbody>
              <tr>
                <td className="w-[45%] align-top">Anjuran pola makan</td>
                <td className="w-4 align-top">:</td>
                <td className="align-top">
                  {ds.anjuranMakan || ds.aturanDiet || "-"}
                </td>
              </tr>
              <tr>
                <td className="align-top">Batasan makanan</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.batasanMakanan || "-"}</td>
              </tr>
            </tbody>
          </table>

          <table className="w-full mb-6">
            <tbody>
              <tr>
                <td className="w-[45%] font-bold align-top">
                  Kebutuhan Spiritual & Psikologis
                </td>
                <td className="w-4 align-top">:</td>
                <td className="align-top">{ds.kebutuhanSpiritual || "-"}</td>
              </tr>
            </tbody>
          </table>

          <h3 className="font-black bg-gray-200 px-2 py-1 mb-2 border border-black uppercase">
            Rencana Pemulangan
          </h3>
          <table className="w-full mb-6">
            <tbody>
              <tr>
                <td className="w-[45%] align-top">Tanggal pemulangan</td>
                <td className="w-4 align-top">:</td>
                <td className="align-top">
                  {ds.tanggalPulang
                    ? new Date(ds.tanggalPulang).toLocaleDateString("id-ID", {
                        day: "numeric",
                        month: "long",
                        year: "numeric",
                      })
                    : "-"}
                </td>
              </tr>
              <tr>
                <td className="align-top">Pendamping</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.pendamping || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Transportasi yang digunakan</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.transportasi || "-"}</td>
              </tr>
              <tr>
                <td className="align-top">Keadaan umum saat pulang</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.keadaanUmum || "-"}</td>
              </tr>
            </tbody>
          </table>

          <h3 className="font-black bg-gray-200 px-2 py-1 mb-2 border border-black uppercase">
            Daftar obat obatan pulang
          </h3>
          <div className="mb-6 pl-4">
            {meds.length > 0 ? (
              <ul className="list-decimal pl-4 space-y-1">
                {meds.map((med: { name: string; dosage?: string; rules?: string; timeToTake?: string }, idx: number) => (
                  <li key={idx}>
                    <span className="font-bold">{med.name}</span> — {med.dosage}
                    <span className="italic ml-2">
                      (Aturan: {med.rules} | Jam minum: {med.timeToTake})
                    </span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="italic text-gray-500">- Tidak ada obat -</p>
            )}
          </div>

          <h3 className="font-black bg-gray-200 px-2 py-1 mb-2 border border-black uppercase">
            Jadwal Kontrol Dokter
          </h3>
          <table className="w-full mb-12">
            <tbody>
              <tr>
                <td className="w-[45%] align-top">Tanggal Kontrol</td>
                <td className="w-4 align-top">:</td>
                <td className="align-top">
                  {ds.jadwalKontrol
                    ? new Date(ds.jadwalKontrol).toLocaleDateString("id-ID", {
                        day: "numeric",
                        month: "long",
                        year: "numeric",
                      })
                    : "-"}
                </td>
              </tr>
              <tr>
                <td className="align-top">Tempat / Poli</td>
                <td className="align-top">:</td>
                <td className="align-top">{ds.tempatKontrol || "-"}</td>
              </tr>
            </tbody>
          </table>

          {isAutoGenerated && (
            <div className="mt-8 mb-6 border-[3px] border-dashed border-gray-400 p-5 rounded-xl bg-gray-50">
              <h3 className="font-black text-lg mb-2 flex items-center gap-2">
                ⚠️ PENTING: Akses Aplikasi Sadulur Care
              </h3>
              <p className="text-sm mb-3">
                Gunakan informasi di bawah ini untuk masuk ke aplikasi, mengisi
                pemantauan harian, dan melihat jadwal kontrol:
              </p>
              <div className="flex flex-col gap-2 mt-2">
                <p className="text-sm font-bold">
                  Link Akses &nbsp;&nbsp;:{" "}
                  <span className="font-mono bg-blue-100 px-3 py-1.5 border border-blue-400 rounded text-base ml-2 text-blue-800">
                    https://sadulur-care.vercel.app
                  </span>
                </p>
                <p className="text-sm font-bold">
                  Email &nbsp;&nbsp;&nbsp;&nbsp;:{" "}
                  <span className="font-mono bg-white px-3 py-1.5 border border-gray-300 rounded text-base ml-2">
                    {userEmail}
                  </span>
                </p>
                <p className="text-sm font-bold">
                  Password :{" "}
                  <span className="font-mono bg-white px-3 py-1.5 border border-gray-300 rounded text-base ml-2">
                    {displayPass}
                  </span>
                </p>
              </div>
              <p className="text-xs text-red-600 italic mt-4 font-bold">
                *Simpan dokumen ini dengan baik. Password bersifat rahasia.
              </p>
            </div>
          )}

          <div className="grid grid-cols-3 text-center mt-12 pt-8">
            <div>
              <p className="mb-20">Pasien / Keluarga,</p>
              <p className="font-bold underline">
                {data.user?.name || "_________________"}
              </p>
            </div>
            <div>
              <p className="mb-20">Perawat,</p>
              <p className="font-bold underline">
                {ds.namaPerawat || "_________________"}
              </p>
            </div>
            <div>
              <p className="mb-20">Dokter Penanggung Jawab,</p>
              <p className="font-bold underline">
                {ds.namaDokter || "_________________"}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
